import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "400",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexMono.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  const pages: string[] = ["Posts", "Projects", "Contact", "About"];

  return (
    <>
      <a
        href="#main-content"
        className="absolute -top-12 left-0 p-4 z-40 bg-light-body text-light-text-primary transition-all focus:top-0"
      >
        Skip to content
      </a>
      <header className="flex flex-col sm:flex-row justify-between items-center p-4 border-b-2 border-light-border">
        <div className="w-full flex flex-row justify-between items-center">
          <Link href="/" className="text-nowrap block font-medium text-xl">
            Hammad Majid
          </Link>
          <button className="block sm:hidden" id="open-button">
            {/* <Fragment set:html={icons.barsBottomRight} /> */}
          </button>
          <button className="hidden sm:hidden" id="close-button">
            {/* <Fragment set:html={icons.xMark} /> */}
          </button>
        </div>
        <nav id="nav-menu" className="hidden sm:block pt-4 sm:pt-0">
          <ul className="text-center space-y-4 sm:space-y-0 sm:flex sm:space-x-4">
            {pages.map((page: string) => (
              <li key={page}>
                <Link
                  href={`/${page.toLowerCase()}`}
                  className="hover:text-light-accent"
                >
                  {page}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </header>
    </>
  );
}
